export const FETCH_HERO_REQUEST = 'FETCH_HERO_REQUEST'
export const FETCH_HERO_SUCCESS = 'FETCH_HERO_SUCCESS'
export const FETCH_HERO_FAILURE = 'FETCH_HERO_FAILURE'

export const FETCH_HEROS_REQUEST = 'FETCH_HEROS_REQUEST'
export const FETCH_HEROS_SUCCESS = 'FETCH_HEROS_SUCCESS'
export const FETCH_HEROS_FAILURE = 'FETCH_HEROS_FAILURE'